// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3d57fdec-bbf6-43e5-a424-68b3201c9a6d";

const char SSID[]               = "Galaxy S20 FE4927";    // Network SSID (name)
const char PASS[]               = "heladera";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "mw89tzSO!zMueRswzV2oDgOx6";    // Secret device password


float caudal;
float conductividad;
float presion;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(caudal, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(conductividad, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(presion, READ, ON_CHANGE, NULL, 1);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
